import { createClient } from 'npm:@supabase/supabase-js@2';
import Stripe from 'npm:stripe@17';
import { corsHeadersFor, handleOptions } from '../_shared/cors.ts';
import { fulfillTicketOrder, fulfillTableBooking } from '../_shared/fulfillment.ts';

// Public, unauthenticated lookup by Stripe checkout session id (the booking-success page's
// only signal). site_orders has no public RLS select policy - it holds customer PII (name,
// email, phone) - so this uses the service_role key and returns only display-safe fields,
// never the full row. The session id itself is the capability: unguessable, generated by
// Stripe, and known only to the customer who was redirected here after paying.
Deno.serve(async (req: Request) => {
  const preflight = handleOptions(req);
  if (preflight) return preflight;

  const cors = corsHeadersFor(req);
  const json = (body: unknown, status = 200) =>
    new Response(JSON.stringify(body), { status, headers: { ...cors, 'Content-Type': 'application/json' } });

  if (req.method !== 'POST') {
    return json({ error: 'Method not allowed' }, 405);
  }

  try {
    const { session_id } = await req.json();
    if (!session_id || typeof session_id !== 'string') {
      return json({ error: 'session_id is required' }, 400);
    }

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
    );

    // Self-heal: normally the Stripe webhook is what marks an order/booking paid and
    // sends the ticket. If that webhook hasn't fired yet - misconfigured endpoint,
    // wrong signing secret, a transient outage, doesn't matter what - this page would
    // otherwise poll forever showing "still confirming" even though Stripe already
    // charged the card. So the moment we see a not-yet-paid row here, ask Stripe
    // directly whether the session actually completed, and if so, do the webhook's
    // job ourselves. Safe to call repeatedly: fulfillment is idempotent.
    const verifyAndFulfillIfPaid = async (kind: 'order' | 'booking', id: string) => {
      const stripeSecretKey = session_id.startsWith('cs_live_')
        ? (Deno.env.get('STRIPE_SECRET_KEY_LIVE') ?? Deno.env.get('STRIPE_SECRET_KEY'))
        : (Deno.env.get('STRIPE_SECRET_KEY_TEST') ?? Deno.env.get('test_SK') ?? Deno.env.get('STRIPE_SECRET_KEY'));
      if (!stripeSecretKey) return;

      try {
        const stripe = new Stripe(stripeSecretKey, {
          apiVersion: '2024-06-20',
          httpClient: Stripe.createFetchHttpClient(),
        });
        const session = await stripe.checkout.sessions.retrieve(session_id);
        if (session.payment_status !== 'paid') return;

        const paymentIntentId =
          (typeof session.payment_intent === 'string' ? session.payment_intent : session.payment_intent?.id) ?? null;

        if (kind === 'order') {
          await fulfillTicketOrder(supabase, id, paymentIntentId);
        } else {
          await fulfillTableBooking(supabase, id, paymentIntentId);
        }
      } catch (err) {
        console.error('site-booking-status: Stripe verification failed', session_id, err);
      }
    };

    const orderSelect =
      'id, status, ticket_code, customer_name, customer_email, quantity, discount_cents, site_ticket_tiers(name), site_events(title, venue_name, start_date)';

    const { data: order } = await supabase
      .from('site_orders')
      .select(orderSelect)
      .eq('stripe_checkout_session_id', session_id)
      .maybeSingle();

    if (order) {
      let current = order;
      if (current.status !== 'paid' || !current.ticket_code) {
        await verifyAndFulfillIfPaid('order', current.id);
        const { data: refreshed } = await supabase
          .from('site_orders')
          .select(orderSelect)
          .eq('stripe_checkout_session_id', session_id)
          .maybeSingle();
        if (refreshed) current = refreshed;
      }

      if (current.status !== 'paid' || !current.ticket_code) {
        return json({ status: current.status });
      }

      const tier = current.site_ticket_tiers as unknown as { name: string } | null;
      const event = current.site_events as unknown as { title: string; venue_name: string; start_date: string } | null;

      return json({
        status: 'paid',
        ticket: {
          ticketCode: current.ticket_code,
          customerName: current.customer_name,
          customerEmail: current.customer_email,
          quantity: current.quantity,
          discountCents: current.discount_cents ?? 0,
          tierName: tier?.name ?? '',
          eventTitle: event?.title ?? 'Your event',
          venueName: event?.venue_name ?? '',
          startDate: event?.start_date ?? '',
        },
      });
    }

    const bookingSelect =
      'id, status, confirmation_code, customer_name, customer_email, guest_count, booking_date, deposit_cents, bottle_subtotal_cents, tax_cents, bottlesup_fee_cents, discount_cents, amount_total_cents, currency, site_table_types(name), site_venues(name), site_venue_time_slots(start_time)';

    const { data: booking, error: bookingError } = await supabase
      .from('site_table_bookings')
      .select(bookingSelect)
      .eq('stripe_checkout_session_id', session_id)
      .maybeSingle();

    if (bookingError || !booking) {
      return json({ status: 'not_found' });
    }

    let currentBooking = booking;
    if (currentBooking.status !== 'paid' || !currentBooking.confirmation_code) {
      await verifyAndFulfillIfPaid('booking', currentBooking.id);
      const { data: refreshed } = await supabase
        .from('site_table_bookings')
        .select(bookingSelect)
        .eq('stripe_checkout_session_id', session_id)
        .maybeSingle();
      if (refreshed) currentBooking = refreshed;
    }

    if (currentBooking.status !== 'paid' || !currentBooking.confirmation_code) {
      return json({ status: currentBooking.status });
    }

    const tableType = currentBooking.site_table_types as unknown as { name: string } | null;
    const venue = currentBooking.site_venues as unknown as { name: string } | null;
    const timeSlot = currentBooking.site_venue_time_slots as unknown as { start_time: string } | null;

    const { data: bottleLines } = await supabase
      .from('site_table_booking_bottles')
      .select('bottle_name, size, quantity, unit_price_cents, line_total_cents')
      .eq('booking_id', currentBooking.id);

    return json({
      status: 'paid',
      booking: {
        confirmationCode: currentBooking.confirmation_code,
        customerName: currentBooking.customer_name,
        customerEmail: currentBooking.customer_email,
        guestCount: currentBooking.guest_count,
        tableTypeName: tableType?.name ?? '',
        venueName: venue?.name ?? '',
        bookingDate: currentBooking.booking_date,
        startTime: timeSlot?.start_time ?? '',
        depositCents: currentBooking.deposit_cents,
        bottleSubtotalCents: currentBooking.bottle_subtotal_cents,
        taxCents: currentBooking.tax_cents,
        bottlesupFeeCents: currentBooking.bottlesup_fee_cents,
        discountCents: currentBooking.discount_cents ?? 0,
        totalCents: currentBooking.amount_total_cents,
        currency: currentBooking.currency,
        bottles: (bottleLines ?? []).map((b) => ({
          name: b.bottle_name,
          size: b.size,
          quantity: b.quantity,
          unitPriceCents: b.unit_price_cents,
          lineTotalCents: b.line_total_cents,
        })),
      },
    });
  } catch (error) {
    console.error('site-booking-status error:', error);
    return json({ error: 'Internal server error' }, 500);
  }
});
